In [4]:
import pandas as pd
a= pd.Series([1,2,3,4,5])
print(a)

a[0:]  #0,1,2,3,4,5

0    1
1    2
2    3
3    4
4    5
dtype: int64

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
#series of Generalized NumPy arrays
import pandas as pd
s= pd.Series([10,20,30,40,50])
print(s)
#series of Specialized Dictionary
a= pd.Series({"math":89,"science":92,"english":85})
print(a)

#You can give index as per your need
b= pd.Series(5,index=[100,200,30])
print(b)

0    10
1    20
2    30
3    40
4    50
dtype: int64
math       89
science    92
english    85
dtype: int64
100    5
200    5
30     5
dtype: int64

In [6]:
#DataFrame it look like a series and its combine a multiple series and give a tabular structure
import pandas as pd
mark  = pd.Series({"math":89,"science":92,"english":85})
grade= pd.Series({"math":"A","science":"B","english":"A+"})
student =pd.DataFrame({"marks":mark,"grades":grade})
#print(student)
student.index
student.values
student.columns


#DataFrame from list of dictionary
student["marks"]
student["grades"]

#Any list of dictionary can be made  into a DataFrame
data=[{'a':i,'b':i*3}
       for i in range(5)]
pd.DataFrame(data)

   a   b
0  0   0
1  1   3
2  2   6
3  3   9
4  4  12

In [7]:
import sys
print(sys.executable)

c:\Users\BALAJI\OneDrive\Desktop\shortcuts\machine learning\ml_env\Scripts\python.exe

In [8]:
#Data Selection in DataFrame
# Also we can add new colum in Dataframe by performing operations on existing columns
import pandas as pd
a=pd.Series([2,4,6,8,10])
b=pd.Series([1,3,5,7,9])
c=pd.DataFrame({'a':a,'b':b})
c
c['result'] = c['a']*c['b']
print(c)
print(c.loc[1:4]) #it gives output of  row and also 4th row
print(c.iloc[1:4]) #it gives output of 2nd row


#Dataframe  as Two-Dimensional Array
c.values
c.T  #it gives an output in transpose/opposite rows and colums  form
c.values[0]  #it gives output of first row and second column value
c['a']
c.iloc[:2,:4]  #it gives output of first two rows and first four columns
c.loc[2:4, 'a':'b']  #it gives output of first two rows and first four columns
c.loc[2,1]=45
c

    a  b  result
0   2  1       2
1   4  3      12
2   6  5      30
3   8  7      56
4  10  9      90
    a  b  result
1   4  3      12
2   6  5      30
3   8  7      56
4  10  9      90
   a  b  result
1  4  3      12
2  6  5      30
3  8  7      56

    a  b  result     1
0   2  1       2   NaN
1   4  3      12   NaN
2   6  5      30  45.0
3   8  7      56   NaN
4  10  9      90   NaN

In [16]:
#Operating on Data in Pandas
import pandas as pd
import numpy as np
rng=np.random.default_rng(2)
ser=pd.Series(rng.integers(0,14,5))
ser

df=pd.DataFrame(rng.integers(0,14,(3,4)), columns=['A','B','C','D'] )#it gives random integer values in 3 rows and 4 columns
df

np.exp(ser)  #it gives exponential value of each element in series

np.sin(df*np.pi/4)  #it gives sine value of each element in dataframe after multiplying with pi/4

A= pd.Series([2,4,6],index=[0,1,2])
B= pd.Series([1,3,5],index=[1,2,3])
A+B  #it gives output of addition of two series and if index is not present in one series then it gives NaN value
A.add(B,fill_value=0)  #it gives output of addition of two series and if index is not present in one series then it gives 0 value

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64